
package net.legoteacher.m;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-12T09:51:29.792+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class UserInfoService_UserInfoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://m.legoteacher.net", "userInfoService");

    private UserInfoService_UserInfoServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserInfoService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserInfoService_Service ss = new UserInfoService_Service(wsdlURL, SERVICE_NAME);
        UserInfoService port = ss.getUserInfoServicePort();  
        
        {
        System.out.println("Invoking readUserInfo...");
        java.lang.String _readUserInfo_clientId = "";
        java.lang.String _readUserInfo_clientPassword = "";
        java.util.List<java.lang.String> _readUserInfo_userIds = null;
        java.util.List<net.legoteacher.m.UserInfo> _readUserInfo__return = port.readUserInfo(_readUserInfo_clientId, _readUserInfo_clientPassword, _readUserInfo_userIds);
        System.out.println("readUserInfo.result=" + _readUserInfo__return);


        }
        {
        System.out.println("Invoking editUserInfo...");
        java.lang.String _editUserInfo_clientId = "";
        java.lang.String _editUserInfo_clientPassword = "";
        net.legoteacher.m.UserInfo _editUserInfo_userInfo = null;
        java.lang.String _editUserInfo__return = port.editUserInfo(_editUserInfo_clientId, _editUserInfo_clientPassword, _editUserInfo_userInfo);
        System.out.println("editUserInfo.result=" + _editUserInfo__return);


        }

        System.exit(0);
    }

}
