package net.legoteacher.m;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-12T09:51:29.928+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://m.legoteacher.net", name = "UserInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserInfoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "readUserInfo", targetNamespace = "http://m.legoteacher.net", className = "net.legoteacher.m.ReadUserInfo")
    @WebMethod
    @ResponseWrapper(localName = "readUserInfoResponse", targetNamespace = "http://m.legoteacher.net", className = "net.legoteacher.m.ReadUserInfoResponse")
    public java.util.List<net.legoteacher.m.UserInfo> readUserInfo(
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "clientPassword", targetNamespace = "")
        java.lang.String clientPassword,
        @WebParam(name = "userIds", targetNamespace = "")
        java.util.List<java.lang.String> userIds
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "editUserInfo", targetNamespace = "http://m.legoteacher.net", className = "net.legoteacher.m.EditUserInfo")
    @WebMethod
    @ResponseWrapper(localName = "editUserInfoResponse", targetNamespace = "http://m.legoteacher.net", className = "net.legoteacher.m.EditUserInfoResponse")
    public java.lang.String editUserInfo(
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId,
        @WebParam(name = "clientPassword", targetNamespace = "")
        java.lang.String clientPassword,
        @WebParam(name = "userInfo", targetNamespace = "")
        net.legoteacher.m.UserInfo userInfo
    );
}
